project:
  type: website
  output-dir: docs


website:
  navbar:
    pinned: true  # 固定导航栏在顶部
    left:
      - text: "<img src='/images/college-logo.png' height='44' style='margin-right:10px;'>"
        href: "index.qmd"
      - text: "<img src='/images/lab-logo.png' height='50'>"
        href: "index.qmd"
    right:
      - text: 首页
        href: "index.qmd"
      - text: 研究方向
        href: "research.qmd"
      - text: 研究成果
        href: "publications.qmd"
      - text: 团队成员
        href: "member-list.qmd"
      - text: 新闻动态
        href: "news.qmd"
      - text: 相册
        href: "gallery.qmd"

format:
  html:
    theme: cosmo
    css: styles.css




